platform :ios, '8.0'

target 'OTScreenShareAccPackKit' do
    pod 'OTAcceleratorPackUtil'
end

target 'OTScreenShareKit' do
    pod 'OTAcceleratorPackUtil'
end

target 'OTScreenShareKitStatic' do
    pod 'OTAcceleratorPackUtil'
end

target 'OTScreenShareKitTests' do
    pod 'Kiwi'
end
