platform :ios, '8.0'

target 'OTTextChatKit' do 
  pod 'OTAcceleratorPackUtil'
end

target 'OTTextChatKitStatic' do 
  pod 'OTAcceleratorPackUtil'
end

target 'OTTextChatKitTests' do 
  pod 'Kiwi'
end