platform :ios, '8.0'

target 'OTTextChatKit' do 
  pod 'OTAcceleratorPackUtil', '~> 1.0.0'
end

target 'OTTextChatKitStatic' do 
  pod 'OTAcceleratorPackUtil', '~> 1.0.0'
end

target 'OTTextChatKitTests' do 
  pod 'Kiwi'
end
