platform :ios, '9.0'

def shared_pods
	pod 'LHToolbar', '= 1.3.0-beta'
    pod 'OTAcceleratorCore'
end

target 'OTAnnotationKit' do
    shared_pods
end

target 'OTAnnotationKitTests' do
  shared_pods
  pod 'Kiwi'
end
