
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'TextChatKit' do 
  pod 'OTAcceleratorPackUtil'
end

target 'TextChatSampleTests' do 
  pod 'Kiwi'
end